@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam classFontColor white

package Logic <<Rectangle>> {
Class LogicManager
Class "{abstract}\nCommand" as Command
Class UndoCommand
Class AddCommand
Class DeleteCommand
}

package Model <<Rectangle>> {
Class Model
}

UndoCommand --|> Command
AddCommand --|> Command
DeleteCommand --|> Command

LogicManager -down-> Command : executes
Command ..> Model

@enduml
